// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoIkC8EgdoZ48-xHe-9RgIjviJ6cVvsOY',
    appId: '1:489719466429:web:b0f56ec9bd67224764aad4',
    messagingSenderId: '489719466429',
    projectId: 'savage-coworking',
    authDomain: 'savage-coworking.firebaseapp.com',
    storageBucket: 'savage-coworking.appspot.com',
    measurementId: 'G-D63Z9S17DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByqNcxNyGOHiZtC3jtCH4NkSE48I4Z7E4',
    appId: '1:489719466429:android:a5f6e0bf727da0bb64aad4',
    messagingSenderId: '489719466429',
    projectId: 'savage-coworking',
    storageBucket: 'savage-coworking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkfF7K4AMRSxq8etM3T63rbbcqIGI8nAg',
    appId: '1:489719466429:ios:12b467c5079bd52164aad4',
    messagingSenderId: '489719466429',
    projectId: 'savage-coworking',
    storageBucket: 'savage-coworking.appspot.com',
    iosClientId: '489719466429-10s5pt5r7utinhrj5d20d7mcpmr96u06.apps.googleusercontent.com',
    iosBundleId: 'dev.kikolator.savageClient',
  );
}
